WalksAndBenches/Controllers/AppController.cs
using WalksAndBenches.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;

namespace WalksAndBenches.Controllers
{
    public class AppController : Controller
    {
        public IActionResult Index()
        {
            return View("Index");
        }

        public IActionResult About()
        {
            return View("About");
        }
    }
}

WalksAndBenches/Controllers/ExploreController.cs
using WalksAndBenches.Models;
using WalksAndBenches.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System.Threading.Tasks;
using System.Collections.Generic;
using System;

namespace WalksAndBenches.Controllers
{
    public class ExploreController : Controller
    {
        private readonly IAssetService _assets;

        public ExploreController(IAssetService assets)
        {
            _assets = assets;
        }

        public async Task<IActionResult> Explore()
        {
            var walks = await _assets.GetWalksToDisplayAsync();

            return View(walks);
        }
    }
}

WalksAndBenches/Controllers/SubmitWalkController.cs
using WalksAndBenches.Models;
using WalksAndBenches.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System.IO;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;

namespace WalksAndBenches.Controllers
{
    public class SubmitWalkController : Controller
    {
        private readonly IAssetService _assets;

        public SubmitWalkController(IAssetService assets)
        {
            _assets = assets;
        }

        [Authorize]
        [HttpGet("submitWalk")]
        public IActionResult SubmitWalk()
        {
            return View();
        }

        [HttpPost("submitWalk")]
        public async Task<IActionResult> SubmitWalk(WalkModel model)
        {
            if (ModelState.IsValid)
            {
                await _assets.SaveWalkAsync(model);
                ViewBag.UserMessage = "Walk saved";
                ModelState.Clear();
            }

            return View();
        }
    }
}

WalksAndBenches/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Benches project: @ViewBag.Title</title>
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/css/walks.css" rel="stylesheet" />
</head>
<body>


    <header class="container">
        <nav class="navbar navbar-dark bg-dark navbar-expand-md">
            <div class="navbar-header">
                <h1 class="navbar-brand"><a class="nav-link" asp-controller="App" asp-action="Index">Benches project</a></h1>
                <button class="navbar-toggler" data-toggle="collapse" data-target="#menu">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
            <span class="">
                @if (this.User.Identity.IsAuthenticated)
                {
                    <span>Logged in as user @this.User.Identity.Name</span>
                }
            </span>
            <ul id="menu" class="navbar-nav navbar-collapse collapse">
                <li class="nav-item"><a class="nav-link" asp-controller="App" asp-action="Index">Home</a></li>
                <li class="nav-item"><a class="nav-link" asp-controller="App" asp-action="About">About</a></li>
                <li class="nav-item"><a class="nav-link" asp-controller="SubmitWalk" asp-action="SubmitWalk">Submit Walk</a></li>
                <li class="nav-item"><a class="nav-link" asp-controller="Explore" asp-action="Explore">Explore</a></li>
                @if (this.User.Identity.IsAuthenticated)
                {
                    <li class="nav-item"><a class="nav-link" asp-controller="Account" asp-action="Logout">Logout</a></li>
                    <li class="nav-item"><a class="nav-link" asp-controller="Account" asp-action="Admin">Admin</a></li>
                }
                else
                {
                    <li class="nav-item"><a class="nav-link" asp-controller="Account" asp-action="Login">Login</a></li>
                }
            </ul>
        </nav>
    </header>

    <section class="container mt-md-4">
        @RenderBody()
    </section>

    <footer class="container">Copyright 2019 bench project</footer>
    
    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script scr="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

        <script src="~/js/index.js"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.4.1.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"></script>
        <script scr="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/index.js"></script>
    </environment>

</body>
</html>